### PR TITLE
Migrate to artifact publish token

### PR DESCRIPTION
**Pull request by rinconjc**
Artifactory secrets are being deprecated.

Please review and merge this change to use the new artifact publish token.

### CODE REVIEW

**Review by pczuj — APPROVED** [review]

**Comment by pczuj** [comment]
Hi @rinconjc after merging this one I was trying to run the release of this module to check if everything is fine (I'm doing the same for 7 other modules as well).

The release failed in https://github.com/atlassian/jvm-tasks/runs/7023264990?check_suite_focus=true with
> Run atlassian-labs/artifact-publish-token@v1.0.1
> Error: Internal server error

Is it something that we've seen before? How can I diagnose the problem?

**Comment by pczuj** [comment]
Hi @rinconjc, can you take a look? ⬆️

**Comment by rinconjc** [comment]
Hi @pczuj ,

Thanks for looking into my PRs.

Let me have a look tomorrow. The logs should show more details.

**Comment by rinconjc** [comment]
Hi @pczuj 

The above issue was caused by request throttling. I've increased the concurrency level. 

Please retry whenever you have a chance

**Comment by pczuj** [comment]
Rerun worked and version 1.2.3 was released.

**Pull request merged**
